# Generated by Django 3.1.3 on 2020-12-30 04:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20201223_2232'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('author', 'content')},
        ),
    ]
